repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.23.3
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/python/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear>=21.4.3]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
