language: python

python:
  - '3.5'
  - '3.6'

env:
  - MARSHMALLOW_VERSION=2
  - MARSHMALLOW_VERSION=3

install:
  - pip install tox
  - pip install coveralls

script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)-ma$MARSHMALLOW_VERSION

after_success:
  - coveralls --verbose
