language: python
cache: pip
install: travis_retry pip install -U tox coveralls
script: tox
after_success: coveralls --verbose

jobs:

  include:

    - { python: '3.9', env: TOXENV=lint }
    - { python: '3.6', env: TOXENV=py36 }
    - { python: '3.9', env: TOXENV=py39 }

    - stage: PyPI Release
      if: tag IS present
      python: '3.9'
      env: TOXENV=py39
      install: skip
      script: echo "Releasing to PyPI..."
      deploy:
        provider: pypi
        on:
          tags: true
        distributions: sdist bdist_wheel
        user: __token__
        password: $PYPI_PASSWORD
