name: build
on:
  push:
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox
      - run: tox -elint
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.6', python: '3.6', os: ubuntu-latest, tox: py36}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: 'PyPy', python: pypy3, os: ubuntu-latest, tox: pypy3}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox codecov
      - run: tox -e${{ matrix.tox }}
      - run: codecov
  release:
    needs: [lint, tests]
    name: PyPI release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
